twig:
  form_themes:
    - '@EasyMedia/form/easy-media.html.twig'

doctrine:
  dbal:
    types:
      easy_media_type: Adeliom\EasyMediaBundle\Types\EasyMediaType

flysystem:
  storages:
    medias.storage:
      adapter: 'local'
      options:
        directory: '%kernel.project_dir%/public/uploads'

easy_media:
  storage_name: 'medias.storage'
  media_entity: App\Entity\EasyMedia\Media
  folder_entity: App\Entity\EasyMedia\Folder
  base_url: 'uploads'
  ignore_files:         '/^\..*/'
  allowed_fileNames_chars: '\._\-\''\s\(\),'
  allowed_folderNames_chars: _\-\s
  unallowed_mimes:
      - php
      - java
      - application
  unallowed_ext:
      - php
      - jav
      - py
      - wav
      - aiff
      - flac
      - mov
      - avi
  last_modified_format: d.m.Y
  pagination_amount:    50